name: Build & publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2

      - uses: actions/upload-artifact@v4.6.2
        with:
          name: pyazul-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4.6.1
        with:
          name: pyazul-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      attestations: write
      contents: read
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4.2.1
        with:
          pattern: pyazul-*
          path: dist
          merge-multiple: true

      - name: Generate artifact attestations
        uses: actions/attest-build-provenance@v2.2.3
        with:
          subject-path: dist/*

      - uses: pypa/gh-action-pypi-publish@release/v1
