name: Continuous Integration

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/ci.yaml'
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/ci.yaml'

env:
  PYTHONUNBUFFERED: 1
  AUTH1: ${{ secrets.AUTH1 }}
  AUTH2: ${{ secrets.AUTH2 }}
  MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
  AZUL_CERT: ${{ secrets.AZUL_CERT }}
  AZUL_KEY: ${{ secrets.AZUL_KEY }}
  MERCHANT_NAME: indexa

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .[dev]

      - name: Run integration tests
        run: python -m pytest tests/integration
