name: Lint Code Base

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - .flake8
      - .isort.cfg
      - .github/workflows/linting.yml

  push:
    branches: [main]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - .flake8
      - .isort.cfg
      - .github/workflows/linting.yml

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4.2.2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.4.0
        env:
          LOG_LEVEL: ERROR
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_JSCPD: false
          VALIDATE_CSS: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_MARKDOWN: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
